@startuml
title АЛЕКСАНДРИТ Как Есть
autonumber

SHOP -> API: INITIATED
SHOP -> API: FILE_UPLOADED
API -> 3DS: FILE_UPLOADED
SHOP -> API: SUBMITTED
API -> MES: SUBMITTED
3DS <-- MES: QUERY 3D
3DS -> MES: GET 3D
MES -> CRM: PRICE_CALCULATED
SALER <- CRM: PRICE_CALCULATED
SALER --> CRM: MANUFACTURING_APPROVED
CRM --> MES: MANUFACTURING_APPROVED
OPR <- MES: MANUFACTURING_APPROVED
OPR --> MES: MANUFACTURING_STARTED
OPR --> MES: MANUFACTURING_COMPLETED
OPR --> MES: PACKAGING
OPR --> MES: SHIPPED
MES -> CRM: SHIPPED
CRM -> SALER: SHIPPED
CRM <-- SALER: CLOSED

left footer


API - Shop API;        3DS - 3D File Storage;        OPR - MES Operator;        RabbitMQ - операции между MES и CRM;        DB - не изображены
end footer
@enduml