@startuml

title Коллектор Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container(vsrv, "Коллектор", "Сервис") {
    Component(ctrl, "Консумер", "Чтение сообщений из KAFKA")
    Component(prd, "DAO", "Запись сообщений в бд")
}
@enduml