@startuml

title Управление Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container(vsrv, "Управление", "Сервис") {
    Component(ctrl, "Контроллер", "POST/GET запросы от пользователя")
    Component(log, "Обработчик", "Управляющая логика")
    Component(prd, "DAO", "Обращения к бд")
    Component(cns, "Http client", "POST запрос в телеметрию")
}
Rel(ctrl, log, "")
Rel(log, prd, "")
Rel(log, cns, "")
@enduml