@startuml

title Запросы Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container(vsrv, "Запросы", "Сервис") {
    Component(ctrl, "Контроллер", "GET запросы от пользователя")
    Component(prd, "DAO", "Обращения к бд")
}
Rel(ctrl, prd, "")
@enduml